name: Deploy Portfolio to Lightsail

on:
  push:
    branches: [master]

concurrency:
  group: deploy-portfolio
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Deploy to Lightsail (pull, install, prisma migrate, build, restart)
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: bitnami
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd /opt/bitnami/portfolio

            # Pull latest
            git fetch --all
            git reset --hard origin/master

            # Ensure env has DATABASE_URL (either via .env on server or uncomment next line)
            # export DATABASE_URL="${{ secrets.DATABASE_URL }}"

            # Install deps (keeps dev deps so Prisma CLI is available)
            npm ci

            # Keep Prisma up to date
            npx prisma generate         # refresh .prisma/client
            npx prisma migrate deploy   # apply pending migrations to prod DB

            # Rebuild app (or skip if you copy CI build artifacts)
            npm run build

            # Optional: slim prod deps after migrate
            # npm prune --production

            # Reload app
            pm2 reload portfolio || pm2 restart portfolio
